# Generated by Django 3.2.9 on 2021-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211201_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_table',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
